version: 1.0.0.{build}
##image: Visual Studio 2015
##services: mssql2014
build: off
artifacts:
- path: db\test_db.dacpac
  name: Mydacpac
deploy:
- provider: Local
  Mydacpac.deploy_database: true
  Mydacpac.drop_objects_not_in_source: true
  Mydacpac.do_not_drop_users: true
  Mydacpac.ignore_permissions: true
  Mydacpac.ignore_user_settings_objects: true
  Mydacpac.ignore_login_sids: true
  Mydacpac.ignore_role_membership: true
  Mydacpac.connection_string: Server=(local)\SQLEXPRESS;Database=my_app;Integrated security=SSPI;
